# Generated by Django 5.0.3 on 2024-05-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_category_comment_like_post_like_postcategory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="name",
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="category",
            name="title",
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
